### ISSUE TITLE
Fish-AIR meta.xml fixes needed

### ISSUE THREAD

**Issue by tubri-github** [tubri/Fish-AIR_API#1]
The following are issues from Minnows workflow , raised by John Bradley:

### Fish-AIR Fixes
The following items are needed before the final dataset used by the workflow can be created and uploaded to datacommons.

The following fixes to the Fish-AIR meta.xml file are needed:
1) Add missing trailing slash for some of the CreateData tags so the XML is parsable.
2) Fix column number values so the values are all unique for each file/column.
3) Finish populating unique term values for the fields so all columns can be referenced by a unique term URI.

**Comment by hlapp** [comment]
Can you say why you labeled this _invalid_?

**Comment by tubri-github** [comment]
> Can you say why you labeled this _invalid_?
I thought this .xml file would be an invalid input for the Minnows workflow, which might have caused confusion with the built-in 'invalid' label on GitHub Issues. I have now created a new label called 'data-issue' to describe issues related to data and have re-labeled this issue accordingly.

**Comment by hlapp** [comment]
Ah I see, thanks for explaining. Normally, the "invalid" label is used to mark an issue as not valid (such as something reported as a bug when in fact it's a feature :-)

**Comment by johnbradley** [comment]
From what I can tell using the [API](https://fishair.org/api/docs#/Multimedia/read_multimedias_multimedias__get) the problems in this issue appear to be fixed. I think this issue can be closed now.

**Comment by tubri-github** [comment]
> From what I can tell using the [API](https://fishair.org/api/docs#/Multimedia/read_multimedias_multimedias__get) the problems in this issue appear to be fixed. I think this issue can be closed now.

Thanks for the update. I'll go ahead and close the issue now. : )
